name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "8.2"
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gb, exif, iconv
        coverage: none

    - name: Run composer install
      run: composer install -n --prefer-dist

      